### ISSUE TITLE
Add piece setup animation

### ISSUE THREAD

**Issue by amatveyakin** [amatveyakin/nutstris#12]
Proposal: make falling piece blocks more ball-shaped and sharpen the corners when the piece is installed, i.e. cannot be longer moved.

**Comment by aeremin** [comment]
@amatveyakin do we have support of it on engine side? Things are quite ready on rendering one.

**Comment by amatveyakin** [comment]
Aaaand now we do :)

**Comment by aeremin** [comment]
Aaaaand now we do support on renderer side. Closing,
